# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: ii-bioinfo-py3
channels:
  - bioconda
  - conda-forge
  - ii-bioinfo
  - defaults
  - anaconda
dependencies:
  # nf core versions
  - anaconda::bz2file
  - bwa=0.7.17
  - bedtools=2.27.1
  - samtools=1.10
  - picard
  - trim-galore=0.4.5
  - python=3.6
  - macs2
  - homer
  - multiqc
  - r-ggpubr
  - r-base
  - r-pheatmap
  - r-upsetr
  - deeptools
  - bioconductor-chipseeker
  - bioconductor-txdb.hsapiens.ucsc.hg19.knowngene
  - bioconductor-dose
  - bioconductor-chippeakanno
  - bioconductor-tracktables
  - bioconductor-rsamtools
  - bioconductor-shortread
  - bioconductor-genomicfeatures
  - bioconductor-genomicranges
  - bioconductor-ensembldb
  - bioconductor-biomart
  - bioconductor-rtracklayer
  - bioconductor-clusterprofiler
  - bioconductor-diffbind
  - bioconductor-atacseqqc
  - bioconductor-motifdb
  - bioconductor-biocparallel
  - idr
  - imagemagick
  - meme
  - ucsc-facount
  - fastqc
  - qualimap
  - markupsafe
  - gawk
  - parallel
  - r-doparallel
  - zip
  - pandoc
  - r-kableextra
  - r-zip
  - r-rmarkdown
  - r-gdata
  - r-dt
  - r-knitr
  - r-openxlsx
  - r-tidyverse
  - r-reshape2
  - r-ggplot2
  - r-catools
  - r-snow
  - r-markdown
  - r-spp
  - r-cairo
  - r-rcolorbrewer
  - r-domc
  - r-knitr
  - r-rmysql
  - r-gplots
  - r-extrafont
  - r-extrafontdb
  - r-r.utils
  - r-evaluate
